--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpzz/RenameUI
build-by-default: true
branches:
- main
projects:
  RenameUI:
    path: ""
libs:
- src: jojoe77777/FormAPI/libFormAPI
  version: ^2.1.1
...
